import './globals.css';
import type { Metadata } from 'next';
import { Atkinson_Hyperlegible } from 'next/font/google';

const Atkinson = Atkinson_Hyperlegible({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={Atkinson.className}>{children}</body>
    </html>
  );
}
